// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/config_api.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/config_api.go -destination=internal/services/mocks/config_mock.go
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigServiceApi is a mock of ConfigServiceApi interface.
type MockConfigServiceApi struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceApiMockRecorder
	isgomock struct{}
}

// MockConfigServiceApiMockRecorder is the mock recorder for MockConfigServiceApi.
type MockConfigServiceApiMockRecorder struct {
	mock *MockConfigServiceApi
}

// NewMockConfigServiceApi creates a new mock instance.
func NewMockConfigServiceApi(ctrl *gomock.Controller) *MockConfigServiceApi {
	mock := &MockConfigServiceApi{ctrl: ctrl}
	mock.recorder = &MockConfigServiceApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigServiceApi) EXPECT() *MockConfigServiceApiMockRecorder {
	return m.recorder
}

// GetConfigValueInt64 mocks base method.
func (m *MockConfigServiceApi) GetConfigValueInt64(k string) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigValueInt64", k)
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetConfigValueInt64 indicates an expected call of GetConfigValueInt64.
func (mr *MockConfigServiceApiMockRecorder) GetConfigValueInt64(k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigValueInt64", reflect.TypeOf((*MockConfigServiceApi)(nil).GetConfigValueInt64), k)
}

// GetConfigValueString mocks base method.
func (m *MockConfigServiceApi) GetConfigValueString(k string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigValueString", k)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetConfigValueString indicates an expected call of GetConfigValueString.
func (mr *MockConfigServiceApiMockRecorder) GetConfigValueString(k any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigValueString", reflect.TypeOf((*MockConfigServiceApi)(nil).GetConfigValueString), k)
}
