// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/storage_api.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/storage_api.go -destination=internal/services/mocks/storage_mock.go
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	v4 "github.com/aws/aws-sdk-go-v2/aws/signer/v4"
	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "go.uber.org/mock/gomock"
)

// MockS3ClientApi is a mock of S3ClientApi interface.
type MockS3ClientApi struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientApiMockRecorder
	isgomock struct{}
}

// MockS3ClientApiMockRecorder is the mock recorder for MockS3ClientApi.
type MockS3ClientApiMockRecorder struct {
	mock *MockS3ClientApi
}

// NewMockS3ClientApi creates a new mock instance.
func NewMockS3ClientApi(ctrl *gomock.Controller) *MockS3ClientApi {
	mock := &MockS3ClientApi{ctrl: ctrl}
	mock.recorder = &MockS3ClientApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3ClientApi) EXPECT() *MockS3ClientApiMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockS3ClientApi) GetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockS3ClientApiMockRecorder) GetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockS3ClientApi)(nil).GetObject), varargs...)
}

// MockS3PresignClientApi is a mock of S3PresignClientApi interface.
type MockS3PresignClientApi struct {
	ctrl     *gomock.Controller
	recorder *MockS3PresignClientApiMockRecorder
	isgomock struct{}
}

// MockS3PresignClientApiMockRecorder is the mock recorder for MockS3PresignClientApi.
type MockS3PresignClientApiMockRecorder struct {
	mock *MockS3PresignClientApi
}

// NewMockS3PresignClientApi creates a new mock instance.
func NewMockS3PresignClientApi(ctrl *gomock.Controller) *MockS3PresignClientApi {
	mock := &MockS3PresignClientApi{ctrl: ctrl}
	mock.recorder = &MockS3PresignClientApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3PresignClientApi) EXPECT() *MockS3PresignClientApiMockRecorder {
	return m.recorder
}

// PresignGetObject mocks base method.
func (m *MockS3PresignClientApi) PresignGetObject(ctx context.Context, params *s3.GetObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignGetObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignGetObject indicates an expected call of PresignGetObject.
func (mr *MockS3PresignClientApiMockRecorder) PresignGetObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignGetObject", reflect.TypeOf((*MockS3PresignClientApi)(nil).PresignGetObject), varargs...)
}

// PresignPutObject mocks base method.
func (m *MockS3PresignClientApi) PresignPutObject(ctx context.Context, params *s3.PutObjectInput, optFns ...func(*s3.PresignOptions)) (*v4.PresignedHTTPRequest, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PresignPutObject", varargs...)
	ret0, _ := ret[0].(*v4.PresignedHTTPRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockS3PresignClientApiMockRecorder) PresignPutObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject", reflect.TypeOf((*MockS3PresignClientApi)(nil).PresignPutObject), varargs...)
}
